### ISSUE TITLE
ThreeWay analysis gone?

### ISSUE THREAD

**Issue by jlboat** [frahik/BMTME#5]
I can't find the ThreeWay data nor the fit function to perform the analysis here. I can find the data by following the publication link: http://hdl.handle.net/11529/10646

However, the fit function doesn't seem to work/exist. I can get the documentation to work, though...

**Comment by frahikLV** [comment]
Hello @jlboat could you tell me where you saw that fitting?

**Comment by jlboat** [comment]
I was trying to replicate the analysis seen in appendix F of https://www.g3journal.org/content/ggg/6/9/2725.full.pdf (A Genomic Bayesian Multi-trait andMulti-environment Model)

Data are loaded using 'data(ThreeWay)' which doesn't appear in the current BMTME package, and later in the appendix, there's a line that reads fit1 <- fit(....), but I can't find that function anywhere and it appears that BMTME is the only library loaded.

**Comment by frahikLV** [comment]
The analysis that is trying to perform was implemented with a package that was built by another author and now is outdated, that version can still be found in the link you provided (http://hdl.handle.net/11529/10646).

This version of BMTME has been completely restructured to be published, so it is not compatible with that implementation.

If you want to use this package I recommend you to check the publication: https://doi.org/10.1534/g3.119.400126

**Comment by jlboat** [comment]
Okay, I'll try to get the older version working, then. Since it's outdated, are there any technical issues with the software I should be concerned about or was it only edited for publication purposes?
